services:
  mysql:
    container_name: electrozone_db
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: electrozone
      MYSQL_ROOT_PASSWORD: hs1234
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - electrozone_mysql_data:/var/lib/mysql
    networks:
      - electrozone_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  springboot:
    container_name: electrozone_app
    #    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://electrozone_db:3306/electrozone?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "hs1234"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - electrozone_network

volumes:
  electrozone_mysql_data:

networks:
  electrozone_network:
